apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arvancloud-dns01-webhook.fullname" . }}
  namespace: {{ include "arvancloud-dns01-webhook.namespace" . }}
  labels:
    {{- include "arvancloud-dns01-webhook.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "arvancloud-dns01-webhook.fullname" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "arvancloud-dns01-webhook.fullname" . }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "arvancloud-dns01-webhook.serviceAccountName" . }}
      containers:
        - name: webhook
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --v={{ .Values.container.verbosity }}
            - --secure-port={{ .Values.container.securePort }}
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
          env:
            - name: GROUP_NAME
              value: {{ .Values.groupName | quote }}
          ports:
            - name: https
              containerPort: {{ .Values.container.securePort }}
          volumeMounts:
            - name: tls
              mountPath: /tls
              readOnly: true
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: tls
          secret:
            secretName: {{ .Values.tls.secretName }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
