apiVersion: v1
kind: Namespace
metadata:
  name: arvancloud-dns01-webhook
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: arvancloud-dns01-webhook
  namespace: arvancloud-dns01-webhook
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: arvancloud-dns01-webhook:secrets-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: arvancloud-dns01-webhook:secrets-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: arvancloud-dns01-webhook:secrets-reader
subjects:
  - kind: ServiceAccount
    name: arvancloud-dns01-webhook
    namespace: arvancloud-dns01-webhook
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: arvancloud-dns01-webhook-selfsign
  namespace: arvancloud-dns01-webhook
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: arvancloud-dns01-webhook-tls
  namespace: arvancloud-dns01-webhook
spec:
  secretName: arvancloud-dns01-webhook-webhook-tls
  privateKey:
    rotationPolicy: Always
  dnsNames:
    - arvancloud-dns01-webhook.arvancloud-dns01-webhook.svc
    - arvancloud-dns01-webhook.arvancloud-dns01-webhook.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: arvancloud-dns01-webhook-selfsign
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arvancloud-dns01-webhook
  namespace: arvancloud-dns01-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: arvancloud-dns01-webhook
  template:
    metadata:
      labels:
        app.kubernetes.io/name: arvancloud-dns01-webhook
    spec:
      serviceAccountName: arvancloud-dns01-webhook
      containers:
        - name: webhook
          image: ghcr.io/immortalvision/arvancloud-dns01-webhook:latest
          imagePullPolicy: IfNotPresent
          args:
            - --v=2
            - --secure-port=6443
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
          env:
            - name: GROUP_NAME
              value: acme.arvancloud.ir
          ports:
            - name: https
              containerPort: 6443
          volumeMounts:
            - name: tls
              mountPath: /tls
              readOnly: true
      volumes:
        - name: tls
          secret:
            secretName: arvancloud-dns01-webhook-webhook-tls
---
apiVersion: v1
kind: Service
metadata:
  name: arvancloud-dns01-webhook
  namespace: arvancloud-dns01-webhook
spec:
  ports:
    - name: https
      port: 443
      targetPort: https
  selector:
    app.kubernetes.io/name: arvancloud-dns01-webhook
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.acme.arvancloud.ir
  annotations:
    cert-manager.io/inject-ca-from: arvancloud-dns01-webhook/arvancloud-dns01-webhook-tls
spec:
  group: acme.arvancloud.ir
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    namespace: arvancloud-dns01-webhook
    name: arvancloud-dns01-webhook
  version: v1alpha1
